steps:
  - label: ':ruby: Test'
    command:
      - "gem install bundler"
      - "bundle install -j $(nproc) --path vendor"
      - "bundle exec rake test"
    plugins:
      - docker#v3.0.1:
          image: "ruby:2.3"
